name: "Prepare Composer"
description: "Sets up the environment with specific global composer package"
inputs:
  php-version:
    description: "Version for PHP runtime"
    required: false
    default: "8.2"
  package:
    description: "Global composer package to set up"
    required: true
  coverage:
    description: "Type of PHP code coverage to set up"
    required: false
    default: "none"
runs:
  using: "composite"
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        coverage: ${{ inputs.coverage }}
        ini-values: error_reporting=E_ALL
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Get composer cache directory
      id: composer-cache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
    - name: Install dependencies
      shell: bash
      run: composer install --no-progress --prefer-dist --classmap-authoritative
    - name: Install required package
      shell: bash
      run: composer global require --no-progress --prefer-dist --classmap-authoritative "${{ inputs.package }}:*"
