name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  PHPUnit:
    strategy:
      matrix:
        operating-system: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
        php-versions: [ '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1' , '8.2']
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          ini-values: error_reporting=E_ALL
      - name: Setup Composer
        uses: ./.github/actions/setup-composer
      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit
      - name: Run PHPUnit
        run: composer test
  PHP_CodeSniffer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          coverage: none
          tools: phpcs
      - name: Setup Composer
        uses: ./.github/actions/setup-composer
      - name: Run PHP_CodeSniffer
        run: composer phpcs -- --no-cache
  PHP-CS-Fixer:
    runs-on: ubuntu-latest
    env:
      PHP_CS_FIXER_IGNORE_ENV: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          coverage: none
          tools: php-cs-fixer
      - name: Setup Composer
        uses: ./.github/actions/setup-composer
      - name: Run PHP Coding Standards Fixer
        run: composer php-cs-fixer -- --dry-run --diff --using-cache=no
  composer-normalize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          coverage: none
          tools: composer-normalize
      - name: Setup Composer
        uses: ./.github/actions/setup-composer
      - name: Run composer-normalize
        run: composer-normalize --dry-run
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          coverage: xdebug
          tools: phpunit
      - name: Setup Composer
        uses: ./.github/actions/setup-composer
      - name: Run PHPUnit with coverage
        run: composer test -- --do-not-cache-result --coverage-clover coverage.xml
      - name: Upload coverage
        uses: codecov/codecov-action@v3
